apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
   app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort : 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: ssh
    port: 22
    protocol: TCP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-image
        imagePullPolicy: Never
