apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-image
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - sh
            - /srcs/livenessprobe.sh
          initialDelaySeconds: 15
          periodSeconds: 3
        ports:
        - containerPort: 21
        - containerPort: 21000
        - containerPort: 21001
        - containerPort: 21002
        - containerPort: 21004
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
spec:
  type: LoadBalancer
  ports:
  - name: ftps-21
    port: 21
    targetPort: 21
  - name: ftps-21000
    port: 21000
  - name: ftps-21001
    port: 21001
  - name: ftps-21002
    port: 21002
  - name: ftps-21003
    port: 21003
  - name: ftps-21004
    port: 21004
  selector:
    app: ftps
